name: Push
on: [push]
jobs:
  do-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
